### ISSUE TITLE
Maestro in homeassistand

### ISSUE THREAD

**Issue by VoetenK** [Chibald/maestrogateway#10]
dear chibald

I am a new user of Home Assistant in Rasberry pi. I still have a lot to learn. Today I spent a whole day installing your repository Maestrogateway. I did not succeed. I try to follow your instructions on the website closely, but I keep getting stuck.

When working with a terminal it does not execute this file "bash install".
When I use docker, the version of docker-compose.yml is higher than version 2 and it doesn't work.

What am I doing wrong and what can I do?

How can I install "Maestro Gateway" on my "Home Assistance"?
I would greatly appreciate it if you could put me on my way.

With best regards
Koen

**Comment by Chibald** [comment]
Hi, I'm using the docker version myself. It is the most convenient way to run the maestro script.

First make sure you have the 3.3 version of docker-compose on your raspberry installed.
Then, edit the _config.py file to suit your needs
Finally run `docker-compose build`
If all went well you should be able to start the container using `docker-compose up`

**Comment by VoetenK** [comment]
Admittedly, I've only been working with Home Assistant in Raspberry Pi for two weeks. 
Still, I feel really stupid. Everything I try fails.
The only thing I know for sure is that Docker engine is installed.
Info Configuration:

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 4.16
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Brussels
version | 0.117.6
virtualenv | false

I can't install Dokker compose. See image.
What am I doing wrong.

I also don't understand the installation instructions. Maybe you can also provide me with detailed information about that.

Regards
Koen

![image](https://user-images.githubusercontent.com/27051683/99075671-2a5fd380-25ba-11eb-88bb-7b4b197cede6.png)

**Comment by Chibald** [comment]
I suggest you take a look at https://github.com/gcgarner/IOTstack .
It will Guide you through the installation process of at least docker and docker compose. IT also has a couple of YouTube video's.

Good luck!
