### ISSUE TITLE
Power_Level command

### ISSUE THREAD

**Issue by NadeoGolf** [Chibald/maestrogateway#11]
Hello,

I am using your script to control my stove with home assistant.
Everything works except the Power_Level command.

Here is an example of what I am using:

topic: SUBmcz
payload_template: '{"Command":"Power_Level", "Value":"13"}'
qos: 0
retain: true

With best regards

**Comment by Chibald** [comment]
Hi,

On my stove there are five power levels available.

So these are valid comands:

`{"Command":"Power_Level", "Value":"1"}`
`{"Command":"Power_Level", "Value":"2"}`
`{"Command":"Power_Level", "Value":"3"}`
`{"Command":"Power_Level", "Value":"4"}`
`{"Command":"Power_Level", "Value":"5"}`

Before you can set the stove to a powel level you should set the Control_Mode to manual like :

`{"Command":"Control_Mode", "Value":"1"}`

back to thermostat mode:

`{"Command":"Control_Mode", "Value":"0"}`

On my stove (the musa hydro) it seems there is a bug that it keep resetting to thermostat mode after a couple of minutes. It also does this when I set the mode manually via console (and disabled script). I asked MCZ about it, but never got an answer. Personally I don't use this feature so I forgot about it to be honest.

**Comment by NadeoGolf** [comment]
Ok, I put 11, 12, 13, 14, 15. I didn't understand

By putting 1, 2, 3, 4 or 5, it works.

Thanks. :D
