### ISSUE TITLE
Switch from automatic to manual mode

### ISSUE THREAD

**Issue by fabimschiller** [Chibald/maestrogateway#36]
Hi,
I love this gateway. Great work! Thanks so much! I use it to integrate my stove into my home automation.
I have one question: How can I switch from automatic mode (dynamic) to manual mode? I tried to use Maestro/Command/Control_Mode and Maestro/Command/Active_Mode, but it looks like neither of them has any effect...
Can you help?
Thanks!

**Comment by VoetenK** [comment]
Hi,
I toggle the control mode for this.
{"topic":"SUBmcz/Control_Mode","payload":"0","_msgid":"4cf04ce6abf27f75"}

**Comment by Chibald** [comment]
Hi @fabimschiller, 

`Maestro/Command/Control_Mode`

Should be the right one. But for me it's also not working. But it is not working for me in the original app as well. When I set to manual, after a while it will revert to automatic. So I guess this is a MCZ issue. (I have Musa Hydro).

As a workaround I use my home automation to send 1 degree higher to the stove when I want power. 

`stoveSetpoint = currentStoveTemperature +1;`

Bit crazy but it works for me ;)

**Comment by fabimschiller** [comment]
Thanks! Works for me now :)
