### ISSUE TITLE
Reset the cashed values when receiving a getinfo in order to send all values to the mqtt subscribers

### ISSUE THREAD

**Issue by tola2000** [Chibald/maestrogateway#37]
When a getinfo explicitly request all the stove info, don't filter out all the values that didn't change but send all values. Only appy filtering of non changed values when it's triggered by the timer...

**Comment by Chibald** [comment]
it 'by design' ;)

this command clears the cache: 
`Maestro/Command/Refresh`

and this one forces a "recuperoinfo":
`Maestro/Command/GetInfo`

You could chain those commands at the mqtt client's end.
But what would be the use case of flooding your mqtt topics with unchanged info I wonder?

**Comment by tola2000** [comment]
That's a solid solution for this use case. I was looking for a client side request to refresh in case of a homa assistant restart or just reconsilation. I missed the refresh command. I'll check the documentation again.

**Comment by tola2000** [comment]
Confirmed to be working :-)
