### ISSUE TITLE
Without Wifi kit

### ISSUE THREAD

**Issue by timmyjp** [Chibald/maestrogateway#5]
Hi, my MCZ Club Hydro 16 doesn't have a wifi module - the cost of a the module is currently around £300 which is crazy high price, so I'm not gong to buy one.  Since you have a good knowledge about the technology, I'd like to ask your opinion - do you think its possible to control the stove without the wifi module somehow? Maybe via raspberry pi + modbus rtu command??

Would love to get your thoughts...

Thanks!

**Comment by Chibald** [comment]
Hi,
I think you have a couple of options if you want to control it via your home automation or app.

The easiest way is probably to send IR commands to the stove by emulating the remote. It will be quite easy to make i think. You'll then be able to do whatever the remote can do, so probably power on / off and power up / down (?). 

But then you'll not get any information back from the stove. I did some research (before finding out that emulating the maestro app was my best option) and i found this : 
https://k3a.me/ir-controller-for-pellet-stove-with-micronova-controller-stufe-e-pellet-aria-ir-telecomando/

Get ready to whip out your soldering iron ;)

**Comment by skate9611** [comment]
Hello, looking for help for a MCZ pellet stove, contact me please.

Discord 
Skate4#1230

Best regards
