### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by AlexFiete** [Chibald/maestrogateway#7]
Hello,
i found a small error. in the file install_daemon in line number 20 a small "s" is missing in commands.py .

I also get an error message when I try to start the service. 

   Loaded: loaded (/etc/systemd/system/maestro.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-04-08 06:49:17 CEST; 14min ago
  Process: 1503 ExecStart=/usr/bin/python /opt/maestro/maestro.py (code=exited, status=1/FAILURE)

Apr 08 06:49:17 raspberrypi systemd[1]: maestro.service: Service RestartSec=100ms expired, scheduling restart.
Apr 08 06:49:17 raspberrypi systemd[1]: maestro.service: Scheduled restart job, restart counter is at 5.
Apr 08 06:49:17 raspberrypi systemd[1]: Stopped MCZ Maestro Equipment Gateway with MQTT Server.
Apr 08 06:49:17 raspberrypi systemd[1]: maestro.service: Start request repeated too quickly.
Apr 08 06:49:17 raspberrypi systemd[1]: maestro.service: Failed with result 'exit-code'.
Apr 08 06:49:17 raspberrypi systemd[1]: Failed to start MCZ Maestro Equipment Gateway with MQTT Server.

Does it mean anything to anyone?

**Comment by Chibald** [comment]
I've added the missing "s".
What's inside the maestro log file. Maybe you're missing a dependency?

**Comment by Chibald** [comment]
I see, _config_.py was missing from the copy phase.

`cp _config_.py /opt/maestro`

I've added it so it should work now.

**Comment by AlexFiete** [comment]
Super thank you it works.
